// Copyright 2026 Glassbox Users
// SPDX-License-Identifier: Apache-2.0

// artifact.go provides ABI hashing, metadata embedding, and metadata parsing
// for generated TypeScript binding files.
//
// Every generated file receives a structured header comment block that encodes
// the ABI hash, contract ID, and generation timestamp.  The validator reads
// these headers back and compares the stored ABI hash against the current
// source ABI to decide whether the bindings are stale.
//
// Header format (embedded as a TypeScript block comment at the top of each
// generated file, before any other content):
//
//	/* @glassbox-bindings-meta
//	 * abi-hash:    <sha256-hex>
//	 * contract-id: <stellar-contract-id-or-empty>
//	 * generated:   <RFC3339-timestamp>
//	 * glassbox:    <semver>
//	 */
package bindings

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/dotandev/glassbox/internal/abi"
	"github.com/dotandev/glassbox/internal/version"
)

const (
	// metaBlockOpen is the opening line of the metadata comment block.
	metaBlockOpen = "/* @glassbox-bindings-meta"
	// metaBlockClose is the closing line of the metadata comment block.
	metaBlockClose = " */"
	// metaPrefix is the prefix for each metadata key-value line.
	metaPrefix = " * "
)

// ArtifactMetadata holds the provenance information embedded in a generated
// binding file.
type ArtifactMetadata struct {
	// ABIHash is the SHA-256 hex digest of the canonical JSON representation of
	// the contract spec that was used to generate the bindings.
	ABIHash string `json:"abiHash"`
	// ContractID is the Stellar contract ID (may be empty when not provided).
	ContractID string `json:"contractId,omitempty"`
	// GeneratedAt is the UTC timestamp at which the bindings were generated.
	GeneratedAt time.Time `json:"generatedAt"`
	// GlassboxVersion is the version of the glassbox binary that generated the
	// bindings.
	GlassboxVersion string `json:"glassboxVersion"`
}

// HashABI computes a stable SHA-256 digest of the contract spec by serialising
// it to canonical JSON (the same format produced by abi.FormatJSON) and hashing
// the resulting bytes.  The canonical JSON representation is deterministic for
// a given spec, so the hash changes if and only if the ABI changes.
func HashABI(spec *abi.ContractSpec) (string, error) {
	canonical, err := abi.FormatJSON(spec)
	if err != nil {
		return "", fmt.Errorf("serialising spec for hashing: %w", err)
	}
	sum := sha256.Sum256([]byte(canonical))
	return hex.EncodeToString(sum[:]), nil
}

// HashABIBytes computes a stable SHA-256 digest directly from raw spec bytes
// (JSON or XDR).  The bytes are first decoded into a ContractSpec and then
// re-serialised to canonical JSON before hashing, so the hash is
// format-independent.
func HashABIBytes(specBytes []byte, format abi.ImportFormat) (string, error) {
	var spec *abi.ContractSpec
	var err error

	switch format {
	case abi.ImportFormatJSON:
		spec, err = abi.ImportFromJSON(specBytes)
	case abi.ImportFormatXDR:
		spec, err = abi.ImportFromXDR(specBytes)
	default:
		// Auto-detect.
		detected := abi.DetectFormat(specBytes)
		switch detected {
		case abi.ImportFormatJSON:
			spec, err = abi.ImportFromJSON(specBytes)
		case abi.ImportFormatXDR:
			spec, err = abi.ImportFromXDR(specBytes)
		default:
			return "", fmt.Errorf("cannot detect ABI format for hashing")
		}
	}
	if err != nil {
		return "", fmt.Errorf("parsing spec for hashing: %w", err)
	}
	return HashABI(spec)
}

// RenderMetadataHeader returns the metadata comment block that is prepended to
// every generated TypeScript file.
func RenderMetadataHeader(meta ArtifactMetadata) string {
	var b strings.Builder
	b.WriteString(metaBlockOpen + "\n")
	fmt.Fprintf(&b, "%sabi-hash:    %s\n", metaPrefix, meta.ABIHash)
	fmt.Fprintf(&b, "%scontract-id: %s\n", metaPrefix, meta.ContractID)
	fmt.Fprintf(&b, "%sgenerated:   %s\n", metaPrefix, meta.GeneratedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "%sglassbox:    %s\n", metaPrefix, meta.GlassboxVersion)
	b.WriteString(metaBlockClose + "\n")
	return b.String()
}

// ParseMetadataHeader scans the content of a generated file and extracts the
// ArtifactMetadata from the embedded header comment block.  Returns
// (nil, nil) when no metadata block is present (e.g. bindings generated by an
// older version of glassbox that did not embed metadata).
func ParseMetadataHeader(content string) (*ArtifactMetadata, error) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	inBlock := false
	kv := make(map[string]string)

	for scanner.Scan() {
		line := scanner.Text()
		if !inBlock {
			if strings.TrimSpace(line) == metaBlockOpen {
				inBlock = true
			}
			continue
		}
		if strings.TrimSpace(line) == strings.TrimSpace(metaBlockClose) {
			break
		}
		// Strip the leading " * " prefix.
		trimmed := strings.TrimPrefix(line, metaPrefix)
		if trimmed == line {
			// Line doesn't start with the expected prefix – skip.
			continue
		}
		idx := strings.Index(trimmed, ":")
		if idx < 0 {
			continue
		}
		key := strings.TrimSpace(trimmed[:idx])
		val := strings.TrimSpace(trimmed[idx+1:])
		kv[key] = val
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scanning file content: %w", err)
	}

	if len(kv) == 0 {
		// No metadata block found.
		return nil, nil //nolint:nilnil
	}

	meta := &ArtifactMetadata{
		ABIHash:         kv["abi-hash"],
		ContractID:      kv["contract-id"],
		GlassboxVersion: kv["glassbox"],
	}
	if ts, ok := kv["generated"]; ok && ts != "" {
		t, err := time.Parse(time.RFC3339, ts)
		if err != nil {
			return nil, fmt.Errorf("parsing generated timestamp %q: %w", ts, err)
		}
		meta.GeneratedAt = t
	}
	return meta, nil
}

// MarshalMetadataJSON serialises ArtifactMetadata to a compact JSON string.
// This is used by the check-bindings command when --json output is requested.
func MarshalMetadataJSON(meta *ArtifactMetadata) (string, error) {
	b, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// currentGlassboxVersion returns the version string to embed in generated
// files.  Falls back to "dev" when the version package has not been
// initialised (e.g. in tests).
func currentGlassboxVersion() string {
	if v := version.Version; v != "" {
		return v
	}
	return "dev"
}

// GetGenerationMetadata returns the metadata embedded in generated files.
// This is used by the verification command to compare generations.
func GetGenerationMetadata(files []GeneratedFile) []ArtifactMetadata {
	var metas []ArtifactMetadata
	for _, f := range files {
		meta, err := ParseMetadataHeader(f.Content)
		if err != nil || meta == nil {
			continue
		}
		metas = append(metas, *meta)
	}
	return metas
}
