// Copyright 2026 Glassbox Users
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/dotandev/glassbox/internal/abi"
	"github.com/dotandev/glassbox/internal/bindings"
	"github.com/spf13/cobra"
)

var (
	checkBindingsOutput       string
	checkBindingsSpecFile     string
	checkBindingsSpecFormat   string
	checkBindingsJSON         bool
	checkBindingsRegenerate   bool
	checkBindingsNetwork      string
	checkBindingsPackage      string
	checkBindingsRuntime      string
	checkBindingsContractID   string
	checkBindingsDebugMeta    bool
	checkBindingsByteVerify   bool
	checkBindingsStrictMode   bool
)

var checkBindingsCmd = &cobra.Command{
	Use:     "check-bindings [wasm-file]",
	GroupID: "development",
	Short:   "Check whether generated TypeScript bindings are up-to-date",
	Long: `Validate generated TypeScript bindings against the current contract ABI.

Glassbox embeds an ABI hash, contract ID, and generation timestamp into every
generated binding file.  check-bindings reads those headers and compares the
stored hash against the hash of the current source ABI (WASM or spec file).

A binding directory is reported as stale when:
  • One or more expected output files are missing.
  • A file's embedded ABI hash does not match the current source ABI.
  • A file has no embedded metadata (generated by an older glassbox version).

With --byte-verify, the command regenerates bindings into a temporary directory
and performs byte-for-byte comparison (excluding timestamps). This detects
formatting drift, line ending differences, and ordering changes.

Spec sources (mutually exclusive):
  <wasm-file>          Extract the contract spec from a compiled WASM binary.
  --spec-file <path>   Load the contract spec from a JSON or XDR ABI file.

Exit codes:
  0  All bindings are up-to-date.
  1  One or more bindings are stale, missing, or have no metadata.
  2  A usage or validation error occurred.

Examples:
  glassbox check-bindings contract.wasm --output ./src/generated
  glassbox check-bindings --spec-file abi.json --output ./src/generated
  glassbox check-bindings contract.wasm --output ./src/generated --json
  glassbox check-bindings contract.wasm --output ./src/generated --regenerate
  glassbox check-bindings contract.wasm --output ./src/generated --byte-verify`,
	Args: cobra.MaximumNArgs(1),
	PreRunE: func(cmd *cobra.Command, args []string) error {
		return validateCheckBindingsFlags(args, checkBindingsOutput, checkBindingsSpecFile, checkBindingsSpecFormat)
	},
	RunE: runCheckBindings,
}

func runCheckBindings(cmd *cobra.Command, args []string) error {
	if checkBindingsOutput == "" {
		checkBindingsOutput = "."
	}

	// ── Load the source ABI ──────────────────────────────────────────────────
	var specBytes []byte
	var specFormat abi.ImportFormat
	var wasmBytes []byte

	switch {
	case checkBindingsSpecFile != "":
		var err error
		specBytes, err = os.ReadFile(checkBindingsSpecFile)
		if err != nil {
			return fmt.Errorf("reading spec file: %w", err)
		}
		switch strings.ToLower(checkBindingsSpecFormat) {
		case "json":
			specFormat = abi.ImportFormatJSON
		case "xdr":
			specFormat = abi.ImportFormatXDR
		default:
			specFormat = abi.DetectFormat(specBytes)
		}

	case len(args) == 1:
		var err error
		wasmBytes, err = os.ReadFile(args[0])
		if err != nil {
			return fmt.Errorf("reading WASM file: %w", err)
		}

	default:
		return fmt.Errorf("provide either a wasm-file argument or --spec-file")
	}

	// ── Run validation ───────────────────────────────────────────────────────
	// If byte-verify is requested, perform byte-level comparison
	if checkBindingsByteVerify {
		return runByteVerify(cmd, args, specBytes, specFormat, wasmBytes)
	}

	report, err := bindings.Validate(bindings.ValidatorConfig{
		OutputDir:  checkBindingsOutput,
		SpecBytes:  specBytes,
		SpecFormat: specFormat,
		WasmBytes:  wasmBytes,
	})
	if err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}

	// ── Output ───────────────────────────────────────────────────────────────
	if checkBindingsJSON {
		if err := printCheckBindingsJSON(cmd, report); err != nil {
			return fmt.Errorf("encoding JSON report: %w", err)
		}
	} else {
		printCheckBindingsText(cmd, report)
	}

	// ── Auto-regenerate if requested and stale ───────────────────────────────
	if checkBindingsRegenerate && report.IsStale {
		fmt.Fprintln(cmd.OutOrStdout(), "\nRegenerating stale bindings…")
		if err := regenerateBindings(args, specBytes, specFormat, wasmBytes); err != nil {
			return fmt.Errorf("regeneration failed: %w", err)
		}
		fmt.Fprintln(cmd.OutOrStdout(), "[OK] Bindings regenerated successfully.")
		return nil
	}

	// Non-zero exit when stale (without --regenerate).
	if report.IsStale {
		return &staleBindingsError{report: report}
	}

	return nil
}

// printCheckBindingsText writes a human-readable validation report.
func printCheckBindingsText(cmd *cobra.Command, report *bindings.ValidationReport) {
	out := cmd.OutOrStdout()
	fmt.Fprintf(out, "Binding directory : %s\n", report.OutputDir)
	fmt.Fprintf(out, "Source ABI hash   : %s\n\n", report.SourceABIHash)

	for _, f := range report.Files {
		icon := statusIcon(f.Status)
		fmt.Fprintf(out, "  %s  %-30s  %s\n", icon, f.Path, string(f.Status))
		if f.Reason != "" {
			fmt.Fprintf(out, "       %s\n", f.Reason)
		}
	}

	fmt.Fprintln(out)
	if report.IsStale {
		fmt.Fprintf(out, "[STALE] %d file(s) are out-of-date. Run with --regenerate to update.\n", report.StaleCount)
	} else {
		fmt.Fprintln(out, "[OK] All bindings are up-to-date.")
	}
}

// printCheckBindingsJSON writes the report as JSON to the command's output writer.
func printCheckBindingsJSON(cmd *cobra.Command, report *bindings.ValidationReport) error {
	enc := json.NewEncoder(cmd.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(report)
}

// statusIcon returns a single-character icon for a ValidationStatus.
func statusIcon(s bindings.ValidationStatus) string {
	switch s {
	case bindings.StatusFresh:
		return "✓"
	case bindings.StatusStale:
		return "✗"
	case bindings.StatusMissing:
		return "?"
	case bindings.StatusNoMetadata:
		return "!"
	default:
		return " "
	}
}

// regenerateBindings re-runs the generator with the same source and the flags
// provided to check-bindings.
func regenerateBindings(
	args []string,
	specBytes []byte,
	specFormat abi.ImportFormat,
	wasmBytes []byte,
) error {
	pkg := checkBindingsPackage
	if pkg == "" && checkBindingsSpecFile != "" {
		base := checkBindingsSpecFile
		// Strip directory and extension.
		if idx := strings.LastIndexAny(base, `/\`); idx >= 0 {
			base = base[idx+1:]
		}
		if dot := strings.LastIndex(base, "."); dot >= 0 {
			base = base[:dot]
		}
		pkg = base
	}
	if pkg == "" && len(args) == 1 {
		base := args[0]
		if idx := strings.LastIndexAny(base, `/\`); idx >= 0 {
			base = base[idx+1:]
		}
		if dot := strings.LastIndex(base, "."); dot >= 0 {
			base = base[:dot]
		}
		pkg = base
	}
	if pkg == "" {
		pkg = "contract"
	}

	cfg := bindings.GeneratorConfig{
		WasmBytes:        wasmBytes,
		SpecBytes:        specBytes,
		SpecFormat:       specFormat,
		OutputDir:        checkBindingsOutput,
		PackageName:      pkg,
		ContractID:       checkBindingsContractID,
		Network:          checkBindingsNetwork,
		RuntimeTarget:    bindings.RuntimeTarget(strings.ToLower(checkBindingsRuntime)),
		IncludeDebugMeta: checkBindingsDebugMeta,
	}

	gen := bindings.NewGenerator(cfg)
	files, err := gen.Generate()
	if err != nil {
		return fmt.Errorf("generating bindings: %w", err)
	}

	for _, file := range files {
		fullPath := checkBindingsOutput + string(os.PathSeparator) + file.Path
		if err := os.MkdirAll(checkBindingsOutput, 0755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}
		if err := os.WriteFile(fullPath, []byte(file.Content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", file.Path, err)
		}
		fmt.Printf("  Regenerated: %s\n", fullPath)
	}
	return nil
}

// staleBindingsError is returned when bindings are stale and --regenerate was
// not passed.  It carries the report so callers can inspect it.
type staleBindingsError struct {
	report *bindings.ValidationReport
}

func (e *staleBindingsError) Error() string {
	return fmt.Sprintf(
		"%d binding file(s) in %q are stale or missing — run `glassbox check-bindings --regenerate` to update",
		e.report.StaleCount,
		e.report.OutputDir,
	)
}

func init() {
	checkBindingsCmd.Flags().StringVarP(&checkBindingsOutput, "output", "o", "",
		"Directory containing the generated binding files (defaults to current directory)")
	checkBindingsCmd.Flags().StringVar(&checkBindingsSpecFile, "spec-file", "",
		"Path to an external contract ABI/spec file (JSON or XDR). Mutually exclusive with wasm-file.")
	checkBindingsCmd.Flags().StringVar(&checkBindingsSpecFormat, "spec-format", "",
		"Format of --spec-file: json or xdr (auto-detected when omitted)")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsJSON, "json", false,
		"Output the validation report as JSON")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsRegenerate, "regenerate", false,
		"Automatically regenerate stale or missing binding files")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsByteVerify, "byte-verify", false,
		"Perform byte-level comparison by regenerating into temp directory (excludes timestamps)")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsStrictMode, "strict", false,
		"Require exact byte match including timestamps (use with fixed generation time)")

	// Regeneration flags (only used when --regenerate is set).
	checkBindingsCmd.Flags().StringVarP(&checkBindingsNetwork, "network", "n", "testnet",
		"Stellar network for regenerated bindings (testnet, mainnet, futurenet)")
	checkBindingsCmd.Flags().StringVarP(&checkBindingsPackage, "package", "p", "",
		"Package name for regenerated bindings (defaults to input filename)")
	checkBindingsCmd.Flags().StringVar(&checkBindingsRuntime, "runtime", "node",
		"Target runtime for regenerated bindings: node, browser, or universal")
	checkBindingsCmd.Flags().StringVar(&checkBindingsContractID, "contract-id", "",
		"Contract ID to embed in regenerated bindings")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsDebugMeta, "debug-metadata", false,
		"Include ABI debug metadata in regenerated bindings")

	_ = checkBindingsCmd.RegisterFlagCompletionFunc("spec-format", completeSpecFormatFlag)
	_ = checkBindingsCmd.RegisterFlagCompletionFunc("network", completeNetworkFlag)
	_ = checkBindingsCmd.RegisterFlagCompletionFunc("runtime", completeBindingsRuntimeFlag)

	rootCmd.AddCommand(checkBindingsCmd)
}

// runByteVerify performs byte-level comparison by regenerating bindings into a
// temporary directory and comparing them with the checked-in files.
func runByteVerify(cmd *cobra.Command, args []string, specBytes []byte, specFormat abi.ImportFormat, wasmBytes []byte) error {
	out := cmd.OutOrStdout()
	fmt.Fprintf(out, "Running byte-level verification for: %s\n\n", checkBindingsOutput)

	// Create temporary directory for regeneration
	tmpDir, err := ioutil.TempDir("", "glassbox-bindings-verify-*")
	if err != nil {
		return fmt.Errorf("creating temp directory: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	// Determine package name
	pkg := checkBindingsPackage
	if pkg == "" && checkBindingsSpecFile != "" {
		base := filepath.Base(checkBindingsSpecFile)
		pkg = base[:len(base)-len(filepath.Ext(base))]
	}
	if pkg == "" && len(args) == 1 {
		base := filepath.Base(args[0])
		pkg = base[:len(base)-len(filepath.Ext(base))]
	}
	if pkg == "" {
		pkg = "contract"
	}

	// Configure generator with fixed timestamp for reproducibility
	cfg := bindings.GeneratorConfig{
		WasmBytes:               wasmBytes,
		SpecBytes:               specBytes,
		SpecFormat:              specFormat,
		OutputDir:               tmpDir,
		PackageName:             pkg,
		ContractID:              checkBindingsContractID,
		Network:                 checkBindingsNetwork,
		RuntimeTarget:            bindings.RuntimeTarget(strings.ToLower(checkBindingsRuntime)),
		IncludeDebugMeta:        checkBindingsDebugMeta,
		NoEmbedArtifactMetadata: false,
	}

	// Use fixed timestamp for strict mode, otherwise normalize during comparison
	if checkBindingsStrictMode {
		cfg.fixedGenerationTime = time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)
	}

	gen := bindings.NewGenerator(cfg)
	files, err := gen.Generate()
	if err != nil {
		return fmt.Errorf("generating bindings in temp directory: %w", err)
	}

	// Write generated files to temp directory
	for _, file := range files {
		fullPath := filepath.Join(tmpDir, file.Path)
		if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
			return fmt.Errorf("creating temp directory: %w", err)
		}
		if err := os.WriteFile(fullPath, []byte(file.Content), 0644); err != nil {
			return fmt.Errorf("writing temp file: %w", err)
		}
	}

	// Compare files
	expectedFiles := map[string]bool{
		"types.ts":                  true,
		"metadata.ts":               true,
		"client.ts":                 true,
		"Glassbox-integration.ts":   true,
		"index.ts":                  true,
		"package.json":              true,
		"README.md":                 true,
	}

	driftFound := false
	for filename := range expectedFiles {
		originalPath := filepath.Join(checkBindingsOutput, filename)
		generatedPath := filepath.Join(tmpDir, filename)

		originalContent, err := os.ReadFile(originalPath)
		if err != nil {
			fmt.Fprintf(out, "  MISSING  %s (file not found in output directory)\n", filename)
			driftFound = true
			continue
		}

		generatedContent, err := os.ReadFile(generatedPath)
		if err != nil {
			fmt.Fprintf(out, "  ERROR    %s (failed to read generated file)\n", filename)
			driftFound = true
			continue
		}

		// Normalize timestamps if not in strict mode
		if !checkBindingsStrictMode {
			originalNormalized := normalizeTimestamps(string(originalContent))
			generatedNormalized := normalizeTimestamps(string(generatedContent))
			
			if originalNormalized == generatedNormalized {
				fmt.Fprintf(out, "  OK       %s\n", filename)
			} else {
				fmt.Fprintf(out, "  DRIFT    %s\n", filename)
				driftFound = true
				// Show first difference
				diff := findFirstDifference(originalNormalized, generatedNormalized)
				if diff != "" {
					fmt.Fprintf(out, "           First difference: %s\n", diff)
				}
			}
		} else {
			// Strict mode: exact byte comparison
			if bytes.Equal(originalContent, generatedContent) {
				fmt.Fprintf(out, "  OK       %s\n", filename)
			} else {
				fmt.Fprintf(out, "  DRIFT    %s (strict mode: exact byte mismatch)\n", filename)
				driftFound = true
				diff := findFirstDifference(string(originalContent), string(generatedContent))
				if diff != "" {
					fmt.Fprintf(out, "           First difference: %s\n", diff)
				}
			}
		}
	}

	fmt.Fprintln(out)
	if driftFound {
		fmt.Fprintf(out, "[DRIFT] Byte-level verification failed.\n")
		fmt.Fprintf(out, "Fix: Regenerate with: glassbox generate-bindings --output %s", checkBindingsOutput)
		if checkBindingsSpecFile != "" {
			fmt.Fprintf(out, " --spec-file %s", checkBindingsSpecFile)
		} else if len(args) == 1 {
			fmt.Fprintf(out, " %s", args[0])
		}
		fmt.Fprintln(out)
		return fmt.Errorf("bindings have drifted")
	}

	fmt.Fprintf(out, "[OK] All bindings are byte-stable.\n")
	return nil
}

// normalizeTimestamps replaces timestamps in metadata headers with a placeholder
// for cross-platform comparison.
func normalizeTimestamps(content string) string {
	// Pattern to match timestamp in metadata header
	timestampPattern := regexp.MustCompile(`generated:   \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z`)
	return timestampPattern.ReplaceAllString(content, "generated:   <TIMESTAMP>")
}

// findFirstDifference returns a string describing the first meaningful difference
// between two strings.
func findFirstDifference(a, b string) string {
	minLen := len(a)
	if len(b) < minLen {
		minLen = len(b)
	}

	for i := 0; i < minLen; i++ {
		if a[i] != b[i] {
			// Show context around the difference
			start := i - 20
			if start < 0 {
				start = 0
			}
			end := i + 20
			if end > minLen {
				end = minLen
			}
			return fmt.Sprintf("at position %d: original=%q, generated=%q", i, a[start:end], b[start:end])
		}
	}

	if len(a) != len(b) {
		return fmt.Sprintf("length mismatch: original=%d, generated=%d", len(a), len(b))
	}

	return ""
}
