// Copyright 2026 Glassbox Users
// SPDX-License-Identifier: Apache-2.0

package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/dotandev/glassbox/internal/abi"
	"github.com/dotandev/glassbox/internal/bindings"
	"github.com/spf13/cobra"
)

var (
	checkBindingsOutput     string
	checkBindingsSpecFile   string
	checkBindingsSpecFormat string
	checkBindingsJSON       bool
	checkBindingsRegenerate bool
	checkBindingsNetwork    string
	checkBindingsPackage    string
	checkBindingsRuntime    string
	checkBindingsContractID string
	checkBindingsDebugMeta  bool
)

var checkBindingsCmd = &cobra.Command{
	Use:     "check-bindings [wasm-file]",
	GroupID: "development",
	Short:   "Check whether generated TypeScript bindings are up-to-date",
	Long: `Validate generated TypeScript bindings against the current contract ABI.

Glassbox embeds an ABI hash, contract ID, and generation timestamp into every
generated binding file.  check-bindings reads those headers and compares the
stored hash against the hash of the current source ABI (WASM or spec file).

A binding directory is reported as stale when:
  • One or more expected output files are missing.
  • A file's embedded ABI hash does not match the current source ABI.
  • A file has no embedded metadata (generated by an older glassbox version).

Spec sources (mutually exclusive):
  <wasm-file>          Extract the contract spec from a compiled WASM binary.
  --spec-file <path>   Load the contract spec from a JSON or XDR ABI file.

Exit codes:
  0  All bindings are up-to-date.
  1  One or more bindings are stale, missing, or have no metadata.
  2  A usage or validation error occurred.

Examples:
  glassbox check-bindings contract.wasm --output ./src/generated
  glassbox check-bindings --spec-file abi.json --output ./src/generated
  glassbox check-bindings contract.wasm --output ./src/generated --json
  glassbox check-bindings contract.wasm --output ./src/generated --regenerate`,
	Args: cobra.MaximumNArgs(1),
	PreRunE: func(cmd *cobra.Command, args []string) error {
		return validateCheckBindingsFlags(args, checkBindingsOutput, checkBindingsSpecFile, checkBindingsSpecFormat)
	},
	RunE: runCheckBindings,
}

func runCheckBindings(cmd *cobra.Command, args []string) error {
	if checkBindingsOutput == "" {
		checkBindingsOutput = "."
	}

	// ── Load the source ABI ──────────────────────────────────────────────────
	var specBytes []byte
	var specFormat abi.ImportFormat
	var wasmBytes []byte

	switch {
	case checkBindingsSpecFile != "":
		var err error
		specBytes, err = os.ReadFile(checkBindingsSpecFile)
		if err != nil {
			return fmt.Errorf("reading spec file: %w", err)
		}
		switch strings.ToLower(checkBindingsSpecFormat) {
		case "json":
			specFormat = abi.ImportFormatJSON
		case "xdr":
			specFormat = abi.ImportFormatXDR
		default:
			specFormat = abi.DetectFormat(specBytes)
		}

	case len(args) == 1:
		var err error
		wasmBytes, err = os.ReadFile(args[0])
		if err != nil {
			return fmt.Errorf("reading WASM file: %w", err)
		}

	default:
		return fmt.Errorf("provide either a wasm-file argument or --spec-file")
	}

	// ── Run validation ───────────────────────────────────────────────────────
	report, err := bindings.Validate(bindings.ValidatorConfig{
		OutputDir:  checkBindingsOutput,
		SpecBytes:  specBytes,
		SpecFormat: specFormat,
		WasmBytes:  wasmBytes,
	})
	if err != nil {
		return fmt.Errorf("validation failed: %w", err)
	}

	// ── Output ───────────────────────────────────────────────────────────────
	if checkBindingsJSON {
		if err := printCheckBindingsJSON(cmd, report); err != nil {
			return fmt.Errorf("encoding JSON report: %w", err)
		}
	} else {
		printCheckBindingsText(cmd, report)
	}

	// ── Auto-regenerate if requested and stale ───────────────────────────────
	if checkBindingsRegenerate && report.IsStale {
		fmt.Fprintln(cmd.OutOrStdout(), "\nRegenerating stale bindings…")
		if err := regenerateBindings(args, specBytes, specFormat, wasmBytes); err != nil {
			return fmt.Errorf("regeneration failed: %w", err)
		}
		fmt.Fprintln(cmd.OutOrStdout(), "[OK] Bindings regenerated successfully.")
		return nil
	}

	// Non-zero exit when stale (without --regenerate).
	if report.IsStale {
		return &staleBindingsError{report: report}
	}

	return nil
}

// printCheckBindingsText writes a human-readable validation report.
func printCheckBindingsText(cmd *cobra.Command, report *bindings.ValidationReport) {
	out := cmd.OutOrStdout()
	fmt.Fprintf(out, "Binding directory : %s\n", report.OutputDir)
	fmt.Fprintf(out, "Source ABI hash   : %s\n\n", report.SourceABIHash)

	for _, f := range report.Files {
		icon := statusIcon(f.Status)
		fmt.Fprintf(out, "  %s  %-30s  %s\n", icon, f.Path, string(f.Status))
		if f.Reason != "" {
			fmt.Fprintf(out, "       %s\n", f.Reason)
		}
	}

	fmt.Fprintln(out)
	if report.IsStale {
		fmt.Fprintf(out, "[STALE] %d file(s) are out-of-date. Run with --regenerate to update.\n", report.StaleCount)
	} else {
		fmt.Fprintln(out, "[OK] All bindings are up-to-date.")
	}
}

// printCheckBindingsJSON writes the report as JSON to the command's output writer.
func printCheckBindingsJSON(cmd *cobra.Command, report *bindings.ValidationReport) error {
	enc := json.NewEncoder(cmd.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(report)
}

// statusIcon returns a single-character icon for a ValidationStatus.
func statusIcon(s bindings.ValidationStatus) string {
	switch s {
	case bindings.StatusFresh:
		return "✓"
	case bindings.StatusStale:
		return "✗"
	case bindings.StatusMissing:
		return "?"
	case bindings.StatusNoMetadata:
		return "!"
	default:
		return " "
	}
}

// regenerateBindings re-runs the generator with the same source and the flags
// provided to check-bindings.
func regenerateBindings(
	args []string,
	specBytes []byte,
	specFormat abi.ImportFormat,
	wasmBytes []byte,
) error {
	pkg := checkBindingsPackage
	if pkg == "" && checkBindingsSpecFile != "" {
		base := checkBindingsSpecFile
		// Strip directory and extension.
		if idx := strings.LastIndexAny(base, `/\`); idx >= 0 {
			base = base[idx+1:]
		}
		if dot := strings.LastIndex(base, "."); dot >= 0 {
			base = base[:dot]
		}
		pkg = base
	}
	if pkg == "" && len(args) == 1 {
		base := args[0]
		if idx := strings.LastIndexAny(base, `/\`); idx >= 0 {
			base = base[idx+1:]
		}
		if dot := strings.LastIndex(base, "."); dot >= 0 {
			base = base[:dot]
		}
		pkg = base
	}
	if pkg == "" {
		pkg = "contract"
	}

	cfg := bindings.GeneratorConfig{
		WasmBytes:        wasmBytes,
		SpecBytes:        specBytes,
		SpecFormat:       specFormat,
		OutputDir:        checkBindingsOutput,
		PackageName:      pkg,
		ContractID:       checkBindingsContractID,
		Network:          checkBindingsNetwork,
		RuntimeTarget:    bindings.RuntimeTarget(strings.ToLower(checkBindingsRuntime)),
		IncludeDebugMeta: checkBindingsDebugMeta,
	}

	gen := bindings.NewGenerator(cfg)
	files, err := gen.Generate()
	if err != nil {
		return fmt.Errorf("generating bindings: %w", err)
	}

	for _, file := range files {
		fullPath := checkBindingsOutput + string(os.PathSeparator) + file.Path
		if err := os.MkdirAll(checkBindingsOutput, 0755); err != nil {
			return fmt.Errorf("creating output directory: %w", err)
		}
		if err := os.WriteFile(fullPath, []byte(file.Content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", file.Path, err)
		}
		fmt.Printf("  Regenerated: %s\n", fullPath)
	}
	return nil
}

// staleBindingsError is returned when bindings are stale and --regenerate was
// not passed.  It carries the report so callers can inspect it.
type staleBindingsError struct {
	report *bindings.ValidationReport
}

func (e *staleBindingsError) Error() string {
	return fmt.Sprintf(
		"%d binding file(s) in %q are stale or missing — run `glassbox check-bindings --regenerate` to update",
		e.report.StaleCount,
		e.report.OutputDir,
	)
}

func init() {
	checkBindingsCmd.Flags().StringVarP(&checkBindingsOutput, "output", "o", "",
		"Directory containing the generated binding files (defaults to current directory)")
	checkBindingsCmd.Flags().StringVar(&checkBindingsSpecFile, "spec-file", "",
		"Path to an external contract ABI/spec file (JSON or XDR). Mutually exclusive with wasm-file.")
	checkBindingsCmd.Flags().StringVar(&checkBindingsSpecFormat, "spec-format", "",
		"Format of --spec-file: json or xdr (auto-detected when omitted)")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsJSON, "json", false,
		"Output the validation report as JSON")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsRegenerate, "regenerate", false,
		"Automatically regenerate stale or missing binding files")

	// Regeneration flags (only used when --regenerate is set).
	checkBindingsCmd.Flags().StringVarP(&checkBindingsNetwork, "network", "n", "testnet",
		"Stellar network for regenerated bindings (testnet, mainnet, futurenet)")
	checkBindingsCmd.Flags().StringVarP(&checkBindingsPackage, "package", "p", "",
		"Package name for regenerated bindings (defaults to input filename)")
	checkBindingsCmd.Flags().StringVar(&checkBindingsRuntime, "runtime", "node",
		"Target runtime for regenerated bindings: node, browser, or universal")
	checkBindingsCmd.Flags().StringVar(&checkBindingsContractID, "contract-id", "",
		"Contract ID to embed in regenerated bindings")
	checkBindingsCmd.Flags().BoolVar(&checkBindingsDebugMeta, "debug-metadata", false,
		"Include ABI debug metadata in regenerated bindings")

	_ = checkBindingsCmd.RegisterFlagCompletionFunc("spec-format", completeSpecFormatFlag)
	_ = checkBindingsCmd.RegisterFlagCompletionFunc("network", completeNetworkFlag)
	_ = checkBindingsCmd.RegisterFlagCompletionFunc("runtime", completeBindingsRuntimeFlag)

	rootCmd.AddCommand(checkBindingsCmd)
}
