// Copyright 2026 Glassbox Users
// SPDX-License-Identifier: Apache-2.0

package sbom_test

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/dotandev/glassbox/internal/sbom"
)

// ─── Component / PURL / SPDXID ───────────────────────────────────────────────

func TestBuildPURL(t *testing.T) {
	cases := []struct {
		eco     sbom.Ecosystem
		name    string
		version string
		want    string
	}{
		{sbom.EcosystemGo, "github.com/foo/bar", "v1.2.3", "pkg:golang/github.com/foo/bar@v1.2.3"},
		{sbom.EcosystemCargo, "serde", "1.0.0", "pkg:cargo/serde@1.0.0"},
		{sbom.EcosystemNPM, "@stellar/stellar-sdk", "14.5.0", "pkg:npm/@stellar/stellar-sdk@14.5.0"},
	}
	for _, c := range cases {
		got := sbom.BuildPURL(c.eco, c.name, c.version)
		if got != c.want {
			t.Errorf("BuildPURL(%q,%q,%q) = %q, want %q", c.eco, c.name, c.version, got, c.want)
		}
	}
}

func TestBuildSPDXID_ContainsNoInvalidChars(t *testing.T) {
	id := sbom.BuildSPDXID(sbom.EcosystemGo, "github.com/foo/bar", "v1.2.3")
	if !strings.HasPrefix(id, "SPDXRef-") {
		t.Errorf("SPDXID %q must start with SPDXRef-", id)
	}
	// SPDX IDs may only contain letters, digits, "." and "-".
	for _, c := range id {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '.' || c == '-') {
			t.Errorf("SPDXID %q contains invalid character %q", id, c)
		}
	}
}

// ─── Go module parser ─────────────────────────────────────────────────────────

func TestParseGoModules_Basic(t *testing.T) {
	input := `
{"Path":"github.com/foo/bar","Version":"v1.2.3","Main":false}
{"Path":"github.com/baz/qux","Version":"v0.1.0","Main":false}
{"Path":"github.com/dotandev/glassbox","Version":"","Main":true}
`
	comps, err := sbom.ParseGoModules(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseGoModules: %v", err)
	}
	if len(comps) != 2 {
		t.Fatalf("len(comps) = %d, want 2 (main module excluded)", len(comps))
	}
	names := map[string]bool{}
	for _, c := range comps {
		names[c.Name] = true
		if c.Ecosystem != sbom.EcosystemGo {
			t.Errorf("component %q: Ecosystem = %q, want go", c.Name, c.Ecosystem)
		}
		if c.PURL == "" {
			t.Errorf("component %q: PURL is empty", c.Name)
		}
		if c.SPDXID == "" {
			t.Errorf("component %q: SPDXID is empty", c.Name)
		}
	}
	if !names["github.com/foo/bar"] || !names["github.com/baz/qux"] {
		t.Errorf("missing expected component; got %v", names)
	}
}

func TestParseGoModules_MainModuleExcluded(t *testing.T) {
	input := `{"Path":"github.com/dotandev/glassbox","Version":"v1.0.0","Main":true}`
	comps, err := sbom.ParseGoModules(strings.NewReader(input))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(comps) != 0 {
		t.Errorf("expected 0 components (main excluded), got %d", len(comps))
	}
}

func TestParseGoModules_Empty(t *testing.T) {
	comps, err := sbom.ParseGoModules(strings.NewReader(""))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(comps) != 0 {
		t.Errorf("expected 0 components for empty input, got %d", len(comps))
	}
}

// ─── Cargo.lock parser ────────────────────────────────────────────────────────

const sampleCargoLock = `
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.210"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "sha256:abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"

[[package]]
name = "serde_json"
version = "1.0.128"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

[[package]]
name = "simulator"
version = "0.1.0"
`

func TestParseCargoLock_Basic(t *testing.T) {
	comps, err := sbom.ParseCargoLock(strings.NewReader(sampleCargoLock))
	if err != nil {
		t.Fatalf("ParseCargoLock: %v", err)
	}
	// "simulator" has no source → local workspace member, must be excluded.
	if len(comps) != 2 {
		t.Fatalf("len(comps) = %d, want 2 (local member excluded)", len(comps))
	}
	for _, c := range comps {
		if c.Ecosystem != sbom.EcosystemCargo {
			t.Errorf("component %q: Ecosystem = %q, want cargo", c.Name, c.Ecosystem)
		}
		if c.PURL == "" {
			t.Errorf("component %q: PURL is empty", c.Name)
		}
		if c.Checksum == "" {
			t.Errorf("component %q: Checksum is empty (should be stripped of sha256: prefix)", c.Name)
		}
		// Checksum must not contain the "sha256:" prefix.
		if strings.Contains(c.Checksum, "sha256:") {
			t.Errorf("component %q: Checksum still contains prefix: %q", c.Name, c.Checksum)
		}
	}
}

func TestParseCargoLock_LocalWorkspaceMemberExcluded(t *testing.T) {
	input := `
[[package]]
name = "my-workspace-crate"
version = "0.1.0"
`
	comps, err := sbom.ParseCargoLock(strings.NewReader(input))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(comps) != 0 {
		t.Errorf("expected 0 components (no source = local), got %d", len(comps))
	}
}

// ─── npm package-lock parser ──────────────────────────────────────────────────

const samplePackageLockV2 = `{
  "name": "glassbox",
  "version": "0.0.1",
  "lockfileVersion": 2,
  "packages": {
    "": {
      "name": "glassbox",
      "version": "0.0.1"
    },
    "node_modules/axios": {
      "version": "1.7.7"
    },
    "node_modules/@stellar/stellar-sdk": {
      "version": "14.5.0"
    },
    "node_modules/typescript": {
      "version": "5.6.3",
      "dev": true
    }
  }
}`

func TestParsePackageLock_V2(t *testing.T) {
	comps, err := sbom.ParsePackageLock(strings.NewReader(samplePackageLockV2))
	if err != nil {
		t.Fatalf("ParsePackageLock: %v", err)
	}
	// "" root entry excluded; 3 real packages remain.
	if len(comps) != 3 {
		t.Fatalf("len(comps) = %d, want 3", len(comps))
	}
	names := map[string]bool{}
	for _, c := range comps {
		names[c.Name] = true
		if c.Ecosystem != sbom.EcosystemNPM {
			t.Errorf("component %q: Ecosystem = %q, want npm", c.Name, c.Ecosystem)
		}
	}
	if !names["axios"] {
		t.Error("missing axios")
	}
	if !names["@stellar/stellar-sdk"] {
		t.Error("missing @stellar/stellar-sdk")
	}
	if !names["typescript"] {
		t.Error("missing typescript")
	}
}

const samplePackageLockV1 = `{
  "name": "glassbox",
  "lockfileVersion": 1,
  "dependencies": {
    "chalk": { "version": "4.1.2" },
    "commander": { "version": "14.0.2" }
  }
}`

func TestParsePackageLock_V1(t *testing.T) {
	comps, err := sbom.ParsePackageLock(strings.NewReader(samplePackageLockV1))
	if err != nil {
		t.Fatalf("ParsePackageLock v1: %v", err)
	}
	if len(comps) != 2 {
		t.Fatalf("len(comps) = %d, want 2", len(comps))
	}
}

// ─── Document generation ──────────────────────────────────────────────────────

func TestGenerateDocument_StructureAndFields(t *testing.T) {
	comps := []sbom.Component{
		{Ecosystem: sbom.EcosystemGo, Name: "github.com/foo/bar", Version: "v1.0.0",
			PURL: sbom.BuildPURL(sbom.EcosystemGo, "github.com/foo/bar", "v1.0.0"),
			SPDXID: sbom.BuildSPDXID(sbom.EcosystemGo, "github.com/foo/bar", "v1.0.0")},
		{Ecosystem: sbom.EcosystemCargo, Name: "serde", Version: "1.0.210",
			PURL: sbom.BuildPURL(sbom.EcosystemCargo, "serde", "1.0.210"),
			SPDXID: sbom.BuildSPDXID(sbom.EcosystemCargo, "serde", "1.0.210"),
			Checksum: "abcdef"},
	}
	ctx := sbom.BuildContext{
		GeneratedAt:    time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC),
		ToolVersion:    "v1.2.3",
		ReleaseVersion: "v1.2.3",
		Commit:         "deadbeef",
	}
	doc := sbom.GenerateDocument(comps, ctx)

	if doc.SPDXVersion != "SPDX-2.3" {
		t.Errorf("SPDXVersion = %q, want SPDX-2.3", doc.SPDXVersion)
	}
	if doc.DataLicense != "CC0-1.0" {
		t.Errorf("DataLicense = %q, want CC0-1.0", doc.DataLicense)
	}
	if doc.SPDXID != "SPDXRef-DOCUMENT" {
		t.Errorf("SPDXID = %q, want SPDXRef-DOCUMENT", doc.SPDXID)
	}
	// Packages = root package + 2 dependencies.
	if len(doc.Packages) != 3 {
		t.Errorf("len(Packages) = %d, want 3", len(doc.Packages))
	}
	if doc.DocumentHash == "" {
		t.Error("DocumentHash is empty; must be computed")
	}
}

func TestGenerateDocument_Deterministic(t *testing.T) {
	comps := []sbom.Component{
		{Ecosystem: sbom.EcosystemGo, Name: "github.com/a/b", Version: "v1.0.0",
			PURL: sbom.BuildPURL(sbom.EcosystemGo, "github.com/a/b", "v1.0.0"),
			SPDXID: sbom.BuildSPDXID(sbom.EcosystemGo, "github.com/a/b", "v1.0.0")},
		{Ecosystem: sbom.EcosystemCargo, Name: "tokio", Version: "1.0.0",
			PURL: sbom.BuildPURL(sbom.EcosystemCargo, "tokio", "1.0.0"),
			SPDXID: sbom.BuildSPDXID(sbom.EcosystemCargo, "tokio", "1.0.0")},
	}
	ctx := sbom.BuildContext{
		GeneratedAt: time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC),
		ReleaseVersion: "v1.0.0",
		Commit: "aaaa",
	}
	doc1 := sbom.GenerateDocument(comps, ctx)
	doc2 := sbom.GenerateDocument(comps, ctx)
	if doc1.DocumentHash != doc2.DocumentHash {
		t.Errorf("DocumentHash not deterministic: %q vs %q", doc1.DocumentHash, doc2.DocumentHash)
	}
}

func TestGenerateDocument_DeduplicatesComponents(t *testing.T) {
	// Same SPDXID from two different inputs (e.g. duplicate transitive dep).
	id := sbom.BuildSPDXID(sbom.EcosystemGo, "github.com/foo/bar", "v1.0.0")
	comps := []sbom.Component{
		{Ecosystem: sbom.EcosystemGo, Name: "github.com/foo/bar", Version: "v1.0.0",
			PURL: sbom.BuildPURL(sbom.EcosystemGo, "github.com/foo/bar", "v1.0.0"), SPDXID: id},
		{Ecosystem: sbom.EcosystemGo, Name: "github.com/foo/bar", Version: "v1.0.0",
			PURL: sbom.BuildPURL(sbom.EcosystemGo, "github.com/foo/bar", "v1.0.0"), SPDXID: id},
	}
	doc := sbom.GenerateDocument(comps, sbom.BuildContext{ReleaseVersion: "v1.0.0"})
	// Packages = 1 root + 1 deduplicated dep.
	if len(doc.Packages) != 2 {
		t.Errorf("len(Packages) = %d after dedup, want 2", len(doc.Packages))
	}
}

// ─── Validation ───────────────────────────────────────────────────────────────

func TestValidate_ValidDocument(t *testing.T) {
	doc := sbom.GenerateDocument([]sbom.Component{
		{Ecosystem: sbom.EcosystemGo, Name: "github.com/x/y", Version: "v1.0.0",
			PURL: sbom.BuildPURL(sbom.EcosystemGo, "github.com/x/y", "v1.0.0"),
			SPDXID: sbom.BuildSPDXID(sbom.EcosystemGo, "github.com/x/y", "v1.0.0")},
	}, sbom.BuildContext{ReleaseVersion: "v1.0.0"})
	if err := sbom.Validate(doc); err != nil {
		t.Errorf("Validate returned error for valid document: %v", err)
	}
}

func TestValidate_NilDocument(t *testing.T) {
	if err := sbom.Validate(nil); err == nil {
		t.Error("Validate(nil) returned nil error, want error")
	}
}

func TestValidate_EmptyPackages(t *testing.T) {
	doc := &sbom.SPDXDocument{
		SPDXVersion:       "SPDX-2.3",
		DataLicense:       "CC0-1.0",
		SPDXID:            "SPDXRef-DOCUMENT",
		Name:              "test",
		DocumentNamespace: "https://example.com/test",
		CreationInfo:      sbom.SPDXCreationInfo{Created: "2026-01-01T00:00:00Z"},
		Packages:          nil,
	}
	if err := sbom.Validate(doc); err == nil {
		t.Error("Validate returned nil for document with no packages, want error")
	}
}

// ─── Marshal / JSON round-trip ────────────────────────────────────────────────

func TestMarshal_ValidJSON(t *testing.T) {
	doc := sbom.GenerateDocument([]sbom.Component{
		{Ecosystem: sbom.EcosystemNPM, Name: "chalk", Version: "4.1.2",
			PURL: sbom.BuildPURL(sbom.EcosystemNPM, "chalk", "4.1.2"),
			SPDXID: sbom.BuildSPDXID(sbom.EcosystemNPM, "chalk", "4.1.2")},
	}, sbom.BuildContext{ReleaseVersion: "v1.0.0"})

	data, err := sbom.Marshal(doc)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	// Must be valid JSON.
	var roundTrip sbom.SPDXDocument
	if err := json.Unmarshal(data, &roundTrip); err != nil {
		t.Fatalf("round-trip JSON unmarshal failed: %v", err)
	}
	if roundTrip.SPDXVersion != "SPDX-2.3" {
		t.Errorf("round-trip SPDXVersion = %q, want SPDX-2.3", roundTrip.SPDXVersion)
	}
}

// ─── GenerateFromFiles integration ───────────────────────────────────────────

func TestGenerateFromFiles_NoInputs(t *testing.T) {
	_, err := sbom.GenerateFromFiles(sbom.GenerateOptions{})
	if err == nil {
		t.Error("GenerateFromFiles with no inputs should return an error")
	}
}

func TestGenerateFromFiles_InlineGoModules(t *testing.T) {
	// Pass inline JSON via GoModulesJSON (starts with '{').
	goJSON := `{"Path":"github.com/foo/bar","Version":"v1.0.0","Main":false}`
	result, err := sbom.GenerateFromFiles(sbom.GenerateOptions{
		GoModulesJSON: goJSON,
		Context: sbom.BuildContext{ReleaseVersion: "v1.0.0"},
	})
	if err != nil {
		t.Fatalf("GenerateFromFiles: %v", err)
	}
	if result.Document == nil {
		t.Fatal("Document is nil")
	}
	if result.ComponentCounts[sbom.EcosystemGo] != 1 {
		t.Errorf("Go component count = %d, want 1", result.ComponentCounts[sbom.EcosystemGo])
	}
}

func TestGenerateFromFiles_MissingOptionalFileIsWarning(t *testing.T) {
	// A non-existent Cargo.lock should produce a warning, not a hard error,
	// as long as at least one source (inline Go JSON) succeeds.
	goJSON := `{"Path":"github.com/foo/bar","Version":"v1.0.0","Main":false}`
	result, err := sbom.GenerateFromFiles(sbom.GenerateOptions{
		GoModulesJSON: goJSON,
		CargoLockPath: "/nonexistent/path/Cargo.lock",
		Context:       sbom.BuildContext{ReleaseVersion: "v1.0.0"},
	})
	if err != nil {
		t.Fatalf("missing optional file should not fail: %v", err)
	}
	if len(result.Warnings) == 0 {
		t.Error("expected at least one warning for missing Cargo.lock")
	}
}

func TestGenerateFromFiles_VersionMatchesLockfile(t *testing.T) {
	// Components from the lockfile must have exact version strings matching
	// what was in the input — no normalisation should alter them.
	goJSON := `{"Path":"github.com/stretchr/testify","Version":"v1.11.1","Main":false}`
	result, err := sbom.GenerateFromFiles(sbom.GenerateOptions{
		GoModulesJSON: goJSON,
		Context:       sbom.BuildContext{ReleaseVersion: "v0.1.0"},
	})
	if err != nil {
		t.Fatalf("GenerateFromFiles: %v", err)
	}
	found := false
	for _, pkg := range result.Document.Packages {
		if pkg.Name == "github.com/stretchr/testify" {
			if pkg.Version != "v1.11.1" {
				t.Errorf("version = %q, want v1.11.1 (must match lockfile exactly)", pkg.Version)
			}
			found = true
		}
	}
	if !found {
		t.Error("github.com/stretchr/testify not found in generated document")
	}
}
